settings:
  prefix: '&#15FF08&lSurvival &8▸ '
  cooldown-type: "HOURS" # Options: "HOURS" (24 hours) or "MIDNIGHT" (Resets at 00:00 every day)
  cooldown-hours: 24

menu:
  title: '&0Günlük Ödül'
  size: 36
  assistant-slot: 31
  assistant-item:
    material: ARROW
    name: '&#00D420Asistan Menüsüne Dön'
  
  available-item:
    material: CHEST_MINECART
    status-lore: '&#00D420Alınabilir'
  
  unavailable-item:
    material: TNT_MINECART
    status-lore: '&cAlınamaz'

rewards:
  oyuncu:
    slot: 10
    permission: 'gunlukodul.oyuncu'
    name: '&#00D420Oyuncu Ödülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
  vip:
    slot: 11
    permission: 'gunlukodul.vip'
    name: '&#fbd42cV&#fcbd30I&#fda634P &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 500'
  vipplus:
    slot: 12
    permission: 'gunlukodul.vipplus'
    name: '&#fbd42cV&#fcb531I&#fd9730P&#fd7a27+ &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 1000'
  uvip:
    slot: 13
    permission: 'gunlukodul.uvip'
    name: '&#ecbbfbU&#e28dfcV&#d85ffcI&#ce31fdP &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 1500'
  uvipplus:
    slot: 14
    permission: 'gunlukodul.uvipplus'
    name: '&#ecbbfbU&#dd76fcV&#ce31fdI&#cc4dfdP&#c969fd+ &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 2000'
  mossvip:
    slot: 15
    permission: 'gunlukodul.mossvip'
    name: '&2M&ao&2s&as&2V&aI&2P &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 2500'
  mossvipplus:
    slot: 16
    permission: 'gunlukodul.mossvipplus'
    name: '&2M&ao&2s&as&2V&aI&2P&a+ &fÖdülü'
    lore:
      - '&7Günlük ödülünüzü'
      - '&7almak için &#ffd500tıklayın.'
      - ''
      - '&#ffd500Durum: %status%'
    commands:
      - 'crates key give %player% gunluk 1'
      - 'eco give %player% 3000'

messages:
  success: '&7Ödülünüzü başarıyla aldınız!'
  no-permission: '&cBu ödülü almak için yeterli yetkiniz yok!'
  already-claimed: '&cBu ödülü zaten aldınız, lütfen yarın tekrar deneyin.'
  error: '&cBir hata oluştu, lütfen daha sonra tekrar deneyin.'
